- src/Api/Authentication.php
Oauth2 twitch's tokens have now an expiration date, and they must be refresh after a time.
I add the implementation of that.
See twitch's documentation:
[Refreshing access tokens](https://dev.twitch.tv/docs/authentication#refreshing-access-tokens)
> Add refresh token

- src/Api/Clips.php
Without the parentheses when checking for the number of channels, the statement will always evaluate to true. That makes the method unusable.
> Fixed getTopClips() always failing

- src/Api/Clips.php
Fixing "game" parameter validation + fixing typo in exception message while at it.
Closes #17
> Fix for Clips::getTopClips

- spec/NewTwitchApi/Cli/CliEndpoints/GetGamesCliEndpointSpec.php
- spec/NewTwitchApi/Cli/CliEndpoints/GetStreamsCliEndpointSpec.php
- spec/NewTwitchApi/Cli/CliEndpoints/GetUsersCliEndpointSpec.php
- spec/NewTwitchApi/Cli/CliEndpoints/GetUsersFollowsCliEndpointSpec.php
- spec/NewTwitchApi/Resources/GamesApiSpec.php
- spec/NewTwitchApi/Resources/StreamsApiSpec.php
- spec/NewTwitchApi/Resources/UsersApiSpec.php
- spec/NewTwitchApi/Webhooks/WebhooksSubscriptionApiSpec.php
- src/NewTwitchApi/Cli/CliEndpoints/GetUsersFollowsCliEndpoint.php
- src/NewTwitchApi/Resources/StreamsApi.php
- src/NewTwitchApi/Resources/UsersApi.php
- src/NewTwitchApi/Webhooks/WebhooksSubscriptionApi.php
- test/NewTwitchApi/Resources/UsersTest.php
Fixes #31 
This changes all IDs to be and expect strings instead of integers. 
I would consider this a breaking change, since I'm changing types in type-strict code. I think when this is released, we should bump to v2.1 instead of v2.0.1. This is major enough that it warrants it, but not major enough to be a v3. Anyone who specifically has 2.0.1 or generic ^2.0 in their composer.json will be fine. Anyone who just has ^2 is kinda asking for trouble anyway and should be aware that they might have issues when upgrading a package like this. (Hopefully those assumingly few will catch this is dev, QA, or CI first. Not sure how we could get the word out. Thoughts?
> Use string instead of int for IDs.

- spec/NewTwitchApi/Webhooks/WebhooksSubscriptionApiSpec.php
- src/NewTwitchApi/Webhooks/WebhooksSubscriptionApi.php
Currently the webhook API type-hints the bearer token as a string, which makes it impossible to not use a bearer token. 
The documentation implies it may be needed, but does not make it mandatory for all topics:
https://dev.twitch.tv/docs/api/webhooks-guide#subscriptions
>Subscription denied — In this case, the request payload explains why the subscription could not be created. **For example, you may not be authorized to access the resource you requested** or you may have exceeded the maximum number of subscriptions.
Currently the only place it is required is the [user changed](https://dev.twitch.tv/docs/api/webhooks-reference/#topic-user-changed) topic when retrieving the email:
>This webhook requires the user:read:email OAuth scope, to get notifications of email changes.
This PR makes …
> Make bearer token optional when subscribing to webhooks

- src/NewTwitchApi/NewTwitchApi.php
- src/NewTwitchApi/Resources/SubscriptionsApi.php
- src/NewTwitchApi/Resources/UsersApi.php
In this PR I've added optional authentication to the Users API allowing you to authenticate ultimately getting a higher rate limit to avoid hitting this cap. Additionally, I've added the Broadcaster Subscriptions API to the Users API, which is documented here: https://dev.twitch.tv/docs/api/reference/#get-broadcaster-s-subscribers
> Optional Authentication for Users API and Broadcasters Subscriptions

- src/NewTwitchApi/Resources/SubscriptionsApi.php
- I've updated the name of the function I passed in a previous PR to `getBroadcasterSubscribers` to match the name of the API call and to allow for the real `getBroadcasterSubscriptions` to be added 
- `getSubscriptionEvents` has been tested to ensure that the `eventId` can be `null` and that if you supply both the `broadcasterId` and `eventId`, despite the documents saying `or` - providing both will work, and the code is cleaner keeping it in one function.
> Completed SubscriptionsApi

- src/NewTwitchApi/NewTwitchApi.php
- src/NewTwitchApi/Resources/GamesApi.php
- src/NewTwitchApi/Resources/ModerationApi.php
- src/NewTwitchApi/Resources/StreamsApi.php
- src/NewTwitchApi/Resources/SubscriptionsApi.php
- src/NewTwitchApi/Resources/UsersApi.php
- src/NewTwitchApi/Resources/VideosApi.php
**Games**
- Added authentication support
- Added `games/top` endpoint
**Users**
- Added `users/extensions` endpoint
- Added `users/extensions/list` endpoint
**Videos**
- Added API files
- Added `videos` endpoint
**Streams**
- Added authentication to `getStreams`
- Added `streams/metadata` endpoint
- Added `streams/markers` endpoint
**Moderation**
- Added API files
- Added `moderation/banned` endpoint
- Added `moderation/banned/events` endpoint
- Added `moderation/moderators` endpoint
- Added `moderation/moderators/events` endpoint (API docs do not show an `after` parameter but it is supported, just missing from the docs
I also put together this quick Google Sheet to help keep track of the current coverage, hopefully this helps: https://bit.ly/2LYSwgp
> Mutliple Helix API Updates

- spec/NewTwitchApi/Webhooks/WebhooksSubscriptionApiSpec.php
- src/NewTwitchApi/Webhooks/WebhooksSubscriptionApi.php
- Add method to subscribe to the [Topic: Subscription Events](https://dev.twitch.tv/docs/api/webhooks-reference/#topic-subscription-events) webhook
- Add spec for the new method
> Add subscribe to subscription events

- src/NewTwitchApi/NewTwitchApi.php
These three APIs should probably return the proper classes and not `UsersApi`.
> Return correct API types

- src/NewTwitchApi/NewTwitchApi.php
- src/NewTwitchApi/Resources/BitsApi.php
- src/NewTwitchApi/Resources/HypeTrainApi.php
- src/NewTwitchApi/Resources/SearchApi.php
- src/NewTwitchApi/Resources/StreamsApi.php
- Normalized order of Resources to be Alphabetical (Twitch's Documentation is becoming out of order, we need to establish our own sorting now)
- Added NewTwitchApi->getBitsApi
- Added BitsApi->getCheermotes
- Added BitsApi->getBitsLeaderboard
- Added NewTwitchApi->getHypeTrainApi
- Added HypeTrainApi->getHypeTrainEvents
- Added NewTwitchApi->getSearchApi
- Added SearchApi->searchCategories
- Added SerachApi->searchChannels
- Added StreamsApi->getChannelInfo
- Added StreamsApi->getStreamKey
> Added numerous missing and new Endpoints to the NewTwitchApi

- .php_cs.dist
- composer.json
- composer.lock
- phpunit.xml.dist
- src/NewTwitchApi/Resources/BitsApi.php
- src/NewTwitchApi/Resources/ClipsApi.php
- src/NewTwitchApi/Resources/HypeTrainApi.php
- src/NewTwitchApi/Resources/ModerationApi.php
- src/NewTwitchApi/Resources/SearchApi.php
- src/NewTwitchApi/Resources/SubscriptionsApi.php
- src/NewTwitchApi/Resources/VideosApi.php
- test/NewTwitchApi/Resources/UsersTest.php
This PR includes:
- **IMPORTANT** Fixed `HypeTrainAPI::getHypeTrainEvents()` use of `$broadcasterId` (FYI @brandinarsenault)
- `php-cs-fixer` fixes for all NewTwitchApi code (especially the newest code added by @brandinarsenault)
- Updated composer to properly namespace our tests
- Updated the PHPUnit config to fix the "missing name attribute" warning
- Removed unused method from `UsersTest`
> CS Clean up and other fixes

- Makefile
Fixes #23 
I believe I found the right way to have CI run `php-cs-fixer`. I've updated the `MAKEFILE` to do a dry run of the fixer (don't actually change files on disk) and stop if it would have changed anything. This should cause CI to fail when CS fixes are needed, preventing the need for bulk fix PRs like #63 
I'd like to wait until #63 is in place before merging this in.
FYI @brandinarsenault So you know to expect this change, with the amount you've been helping with this library.
> Add CS check to `make test`. Should run in CI now.

- src/NewTwitchApi/NewTwitchApi.php
- src/NewTwitchApi/Resources/AbstractResource.php
- src/NewTwitchApi/Resources/AdsApi.php
- src/NewTwitchApi/Resources/ClipsApi.php
- Added `AbstractResource->postApi` for Post API calls
- Added `NewTwitchApi->getAdsApi`
- Added `AdsApi->startCommercial` 
- Added `ClipsApi->createClip`
- Removed Optional Bearer from AbstractResource, Enforced
> Add Endpoints startCommercial and createClip, Removed Optional Bearer

- src/NewTwitchApi/Resources/VideosApi.php
The `type` parameter of the `getVideos()` call of the VideosApi is never parsed due to an apparent copy/paste mistake.
Fixed that in this PR.
> VideosApi parameter fix

- src/NewTwitchApi/Resources/StreamsApi.php
Add support for the [Get Stream Tags](https://dev.twitch.tv/docs/api/reference#get-stream-tags) endpoint.
> Add Get Stream Tags endpoint support

- .php_cs.dist
- src/NewTwitchApi/Auth/OauthApi.php
- src/NewTwitchApi/Resources/AdsApi.php
- src/NewTwitchApi/Resources/BitsApi.php
- src/NewTwitchApi/Resources/ClipsApi.php
- src/NewTwitchApi/Resources/EntitlementsApi.php
- src/NewTwitchApi/Resources/HypeTrainApi.php
- src/NewTwitchApi/Resources/ModerationApi.php
- src/NewTwitchApi/Resources/SearchApi.php
- src/NewTwitchApi/Resources/StreamsApi.php
- src/NewTwitchApi/Resources/SubscriptionsApi.php
- src/NewTwitchApi/Resources/VideosApi.php
- test/NewTwitchApi/Resources/UsersTest.php
There's been a bit of messy code added, myself included, so I'm updating the php-cs-fixer rules to fix that, so we can keep the code base clean and consistent. 
Mostly what's being fixed here is:
- Indentation and spacing
- Use `'` instead of `"` 
- Trailing commas
- Blank line before `return`
What I've done is enable the `@Symfony` rules, with a few exceptions:
- Disabled `phpdoc_annotation_without_dot`
- Disabled `phpdoc_no_alias_tag`
- Disabled `phpdoc_separation`
- Disabled `yoda_style`
Rule descriptions can be found here: https://github.com/FriendsOfPhp/PHP-CS-Fixer#rules
> Updated php-cs-fixer rules and fixes

- spec/NewTwitchApi/Resources/StreamsApiSpec.php
- src/NewTwitchApi/Resources/StreamsApi.php
- Added `getStreamsByGameId` helper
- Added `getStreamsByLanguage` helper
- Removed support for Community IDs, no longer in the API
> getStreams Improvements

- spec/NewTwitchApi/Resources/UsersApiSpec.php
- src/NewTwitchApi/Resources/AbstractResource.php
- src/NewTwitchApi/Resources/AdsApi.php
- src/NewTwitchApi/Resources/SubscriptionsApi.php
- src/NewTwitchApi/Resources/UsersApi.php
- Added bodyParams to the Abstract Functions
- Added deleteApi function
- Fixed a bug with startCommercial #90 
- Resolved Doc Link issue in #76 
- Add Users: deleteUserFollow and Spec
The decision to use validation code in the Abstract Resource was made to avoid refactoring the tests. We could, naturally, just pass an empty body, however, this would require the rewriting of all of our tests to have an empty body. This could likely be improved in the future, for all of the calls, as we're repeating code in the Abstract quite frequently.
> Add bodyParams and Function Updates

- .github/workflows/test.yaml
This PR resolves a test build issue related to PHP 7.2 and 7.3 by removing them from the `test.yaml`
> Remove PHP 7.2, 7.3, add 8.0 to GHA

- README.md
- spec/NewTwitchApi/Auth/AuthGuzzleClientSpec.php
- spec/NewTwitchApi/HelixGuzzleClientSpec.php
- src/NewTwitchApi/Auth/AuthGuzzleClient.php
- src/NewTwitchApi/Auth/OauthApi.php
- src/NewTwitchApi/HelixGuzzleClient.php
- src/NewTwitchApi/Webhooks/WebhooksSubscriptionApi.php
I am proposing a small PR to fix a deprecation warning when using Guzzle 7.1+
> User Deprecated: The "GuzzleHttp\Client" class is considered final. It may change without further notice as of 
its next major version. You should not extend it from "NewTwitchApi\Auth\AuthGuzzleClient".
Extending Guzzle\Client is deprecated since Guzzle 7.1 and [the class is annotated as @final](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L15). The class will be actually final in Guzzle 8.0.
See guzzle/guzzle#2521
This would be a BC change, but since [you're thinking of making a 5.0 release](https://github.com/nicklaw5/twitch-api-php/pull/117#issuecomment-849874108), this would be the time.
> Do not extend Guzzle\Client

- spec/NewTwitchApi/NewTwitchApiSpec.php
- spec/NewTwitchApi/Resources/EventSubApiSpec.php
- spec/NewTwitchApi/Resources/ScheduleApiSpec.php
- src/NewTwitchApi/NewTwitchApi.php
- src/NewTwitchApi/RequestGenerator.php
- src/NewTwitchApi/Resources/AbstractResource.php
- src/NewTwitchApi/Resources/EventSubApi.php
- src/NewTwitchApi/Resources/ScheduleApi.php
**CORE**
- Allow Optional Auth in Request Generator
- Cleanup Headers in Request Generator
- Added `getApiWithOptionalAuth` for explicit calls with optional authentication (since all endpoints but 1 require auth at this time)
**NEW FEATURES**
- Added `ScheduleApi`
- Added `ScheduleApi` -> `getChannelStreamSchedule`
- Added `ScheduleApi` -> `getChanneliCalendar` (optional auth)
- Added `ScheduleApi` -> `updateChannelStreamSchedule`
- Added `ScheduleApi` -> `createChannelStreamScheduleSegment`
- Added `ScheduleApi` -> `updateChannelStreamScheduleSegment`
- Added `ScheduleApi` -> `deleteChannelStreamScheduleSegment`
**CHANGES**
- Promote `EventSubApi` -> `channel.subscription.message` to v1
> v5.0.5: Add Schedules API

- .github/workflows/test.yaml
- .gitignore
- .php-cs-fixer.dist.php
- Makefile
- composer.json
- spec/TwitchApi/Resources/ChatApiSpec.php
- spec/TwitchApi/Resources/EventSubApiSpec.php
- spec/TwitchApi/Resources/HypeTrainApiSpec.php
- spec/TwitchApi/Resources/ModerationApiSpec.php
- spec/TwitchApi/Resources/RaidsApiSpec.php
- spec/TwitchApi/Resources/WhispersApiSpec.php
- spec/TwitchApi/TwitchApiSpec.php
- src/Resources/ChatApi.php
- src/Resources/EventSubApi.php
- src/Resources/HypeTrainApi.php
- src/Resources/ModerationApi.php
- src/Resources/RaidsApi.php
- src/Resources/WhispersApi.php
- src/TwitchApi.php
**BREAKING CHANGES**
- Removed `getBannedEvents` and `getModeratorEvents` - [Announcement](https://discuss.dev.twitch.tv/t/deprecation-of-twitch-api-event-endpoints-that-supported-websub-based-webhooks/35137)
- Removed `id` parameter from `getHypeTrainEvents` (this function was broken anyways) - [Announcement](https://discuss.dev.twitch.tv/t/get-hype-train-events-api-endpoint-id-query-parameter-deprecation/37613)
- Removed `user_id` parameter from `checkAutoModStatus` - [Announcement](https://discuss.dev.twitch.tv/t/upcoming-changes-to-the-check-automod-status-api-endpoint/38512)
**CHANGES**
- Promoted `EventSub` -> `extension.bits_transaction.crate` to version `1`
**NEW FEATURES**
- Added `user_id` parameter to `getEventSubSubscription`
- Added `ChatApi` -> `getChatSettings`
- Added …
> v7.0.0: Endpoint Coverage

- spec/TwitchApi/Resources/BitsApiSpec.php
- spec/TwitchApi/Resources/ClipsApiSpec.php
- spec/TwitchApi/Resources/EntitlementsApiSpec.php
- spec/TwitchApi/Resources/EventSubApiSpec.php
- spec/TwitchApi/Resources/ModerationApiSpec.php
- spec/TwitchApi/Resources/SearchApiSpec.php
- spec/TwitchApi/TwitchApiSpec.php
- src/Resources/EntitlementsApi.php
- src/Resources/EventSubApi.php
- src/Resources/ModerationApi.php
I added a note to #136, since there have been no requests for the Extensions category yet, and this isn't likely to be needed in a PHP project, I'll consider endpoint coverage complete with this PR. [[Note]](https://github.com/nicklaw5/twitch-api-php/issues/136#issuecomment-1237225319)
- `updateDropEntitlements` now allows you to specify no parameters, in line with the API Docs
- Added Missing Testing Coverage for many older functions
- Added `first` parameter to `getBannedUsers`
- Added `first` parameter to `getModerators`
- Added `EventSub` -> `drop.entitlement.grant`
> Finish Endpoint and Testing Coverage

- spec/TwitchApi/Resources/CharityApiSpec.php
- spec/TwitchApi/Resources/ChatApiSpec.php
- spec/TwitchApi/Resources/EventSubApiSpec.php
- spec/TwitchApi/Resources/ModerationApiSpec.php
- spec/TwitchApi/TwitchApiSpec.php
- src/Resources/CharityApi.php
- src/Resources/ChatApi.php
- src/Resources/EventSubApi.php
- src/Resources/ModerationApi.php
- src/TwitchApi.php
* Added `CharityApi`
* Added `CharityApi` -> `getCharityCampaign`
* Added `CharityApi` -> `getCharityCampaignDonations`
* Added `ModerationApi` -> `getShieldModeStatus`
* Added `ModerationApi` -> `updateShieldModeStatus`
* Added `ChatApi` -> `getChatters`
* Added `EventSub` -> `channel.charity_campaign.start`
* Added `EventSub` -> `channel.charity_campaign.progress`
* Added `EventSub` -> `channel.charity_campaign.stop`
* Added `EventSub` -> `channel.charity_campaign.donate`
* Added `EventSub` -> `channel.shield_mode.begin`
* Added `EventSub` -> `channel.shield_mode.end`
> Add Charity APIs/Subs, Chat and Moderation API Additions

- spec/TwitchApi/Resources/EventSubApiSpec.php
- src/Resources/EventSubApi.php
in case of subscription `drop.entitlement.grant` we must use `is_batching_enabled: true` param https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/#drop-entitlement-grant-notification-example
otherwise will get an exception
```
{
"error":"Bad Request",
"status":400,
"message":"is_batching_enabled must be true for drop.entitlement.grant subscriptions"
}
```
> drop.entitlement.grant subscription must have is_batching_enabled param

- spec/TwitchApi/Resources/EntitlementsApiSpec.php
- src/Resources/EntitlementsApi.php
add `fulfillment_status` filter to getDropsEntitlements method according to the doc https://dev.twitch.tv/docs/api/reference/#get-drops-entitlements
**note**:  ideally it should be after `$gameId` parameter, but i afraid to break compatibility
> add FulfillmentStatus filter to getDropsEntitlements method

- spec/TwitchApi/Resources/GoalsApiSpec.php
- spec/TwitchApi/TwitchApiSpec.php
- src/Resources/GoalsApi.php
- src/TwitchApi.php
Feature addition for the simple [goals endpoint](https://dev.twitch.tv/docs/api/reference#get-creator-goals).
Example:
`$response = $twitchApi->getGoalsApi()->getGoals($twitch_access_token, $twitch_broadcaster_id);`
Note: The Twitch API docs labels this endpoint as "Get Creator Goals", but the endpoint itself is just goals, so I went with "Goals" instead of "CreatorGoals".
> Add in Goals API
