nicklaw5/twitch-api-php

.travis.yml, composer.json, src/Api/Authentication.php, src/TwitchApi.php, test/TwitchApiTest.php
This closes #1 
- Test on PHP 5.6 and greater
- Fix test issues
=> Configure Travis-CI

src/TwitchApi.php, test/TwitchApiTest.php
Hello! :) 
I fixed the issue #4, added a test case and optimized the TestCase using [PHPUnit test-dependacies](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.test-dependencies).
Build Result : https://travis-ci.org/RickyNotaro/twitch-api-php/builds/211177094
=> Fixing issue #4

src/Api/Clips.php
https://dev.twitch.tv/docs/v5/reference/clips/#get-clip
Endpoint does not need a channel
=> Fix getClip

.travis.yml, Makefile
Run both phpunit and phpspec as part of CI.
=> Test with both phpunit and phpspec

composer.json
=> Add echosa as an author in composer.json.

spec/NewTwitchApi/Webhooks/WebhooksSubscriptionApiSpec.php, src/NewTwitchApi/Webhooks/WebhooksSubscriptionApi.php
=> Add support for unsubscribing from webhooks

README.md, src/NewTwitchApi/Resources/StreamsApi.php
Modified the following Endpoints to added optional bearer token for Helix:
- getStreamForUserId
- getStreamForUsername
=> Added Bearer for getStreamForUserId and getStreamForUsername

.gitignore, .travis.yml, composer.json, composer.lock, test/NewTwitchApi/Resources/UsersTest.php
As discovered in https://github.com/nicklaw5/twitch-api-php/pull/60#issuecomment-642774007 this library doesn't currently work with PHP 7.4. This PR does what I believe to be the bare minimum to fix that.
Relates to #60
=> Update composer.json for PHP 7.4

spec/NewTwitchApi/Resources/GamesApiSpec.php, spec/NewTwitchApi/Resources/StreamsApiSpec.php, spec/NewTwitchApi/Resources/UsersApiSpec.php, src/NewTwitchApi/Resources/AbstractResource.php, src/NewTwitchApi/Resources/ClipsApi.php, src/NewTwitchApi/Resources/GamesApi.php, src/NewTwitchApi/Resources/ModerationApi.php, src/NewTwitchApi/Resources/StreamsApi.php, src/NewTwitchApi/Resources/SubscriptionsApi.php, src/NewTwitchApi/Resources/UsersApi.php, src/NewTwitchApi/Resources/VideosApi.php, src/NewTwitchApi/Resources/WebhooksApi.php, test/NewTwitchApi/Resources/UsersTest.php
- Updated CallApi function to force bearer
- Endpoints from all classes were updated to force bearer token
=> Update New API Endpoints to force bearer token

src/Api/Authentication.php, src/Api/Bits.php, src/Api/ChannelFeed.php, src/Api/Channels.php, src/Api/Chat.php, src/Api/Clips.php, src/Api/Collections.php, src/Api/Communities.php, src/Api/Games.php, src/Api/Ingests.php, src/Api/Root.php, src/Api/Search.php, src/Api/Streams.php, src/Api/Teams.php, src/Api/Users.php, src/Api/Videos.php, src/TwitchRequest.php
Fixes #33 
Old code, but easy enough to do. Nice to clear out more issues, especially old ones. :-)
=> Use string instead of json in PHPDoc.

src/NewTwitchApi/NewTwitchApi.php, src/NewTwitchApi/Resources/EntitlementsApi.php
Returns the aws url to upload the entitlement package
https://dev.twitch.tv/docs/api/reference/#create-entitlement-grants-upload-url
=> +added support for 'entitlements/upload'

src/NewTwitchApi/Resources/SearchApi.php
Typo made it impossible to search for categories
searchChannels was searching categories
=> Fix issue with searching categories

spec/NewTwitchApi/NewTwitchApiSpec.php, spec/NewTwitchApi/Resources/AnalyticsApiSpec.php, spec/NewTwitchApi/Resources/BitsApiSpec.php, spec/NewTwitchApi/Resources/EntitlementsApi.php, spec/NewTwitchApi/Resources/GamesApiSpec.php, spec/NewTwitchApi/Resources/TagsApiSpec.php, spec/NewTwitchApi/Resources/UsersApiSpec.php, spec/NewTwitchApi/Resources/WebhooksApiSpec.php, src/NewTwitchApi/NewTwitchApi.php, src/NewTwitchApi/Resources/AbstractResource.php, src/NewTwitchApi/Resources/AnalyticsApi.php, src/NewTwitchApi/Resources/BitsApi.php, src/NewTwitchApi/Resources/EntitlementsApi.php, src/NewTwitchApi/Resources/TagsApi.php, src/NewTwitchApi/Resources/UsersApi.php
Added these APIs:
- NewTwitchApi->getAnalyticsApi
- NewTwitchApi->getTagsApi
Added these endpoints:
- BitsApi->getExtensionTransactions
- AnalyticsApi->getExtensionAnalytics
- AnalyticsApi->getGameAnalytics
- EntitlementsApi->getStatusCode
- EntitlementsApi->redeemCode
- TagsApi->getAllStreamTags
- TagsApi->getStreamTags
- UsersApi->createUserFollow
Added missing Link Docs for:
- EntitlementsApi->getEntitlementGrantsUploadURL
=> Added 9 Endpoints over 5 APIs, 2 new APIs created

spec/NewTwitchApi/Webhooks/WebhooksSubscriptionApiSpec.php, src/NewTwitchApi/Webhooks/WebhooksSubscriptionApi.php
- Added arguments for a OAuth token in the three unsubscribe functions.
- Updated arguments for tests.
=> Added bearer token support for unsubscribe methods #7

spec/NewTwitchApi/NewTwitchApiSpec.php, spec/NewTwitchApi/Resources/ChannelPointsApiSpec.php, src/NewTwitchApi/NewTwitchApi.php, src/NewTwitchApi/Resources/ChannelPointsApi.php
- Added `ChannelPointsApi`
- Added `getCustomReward`
- Added `getCustomRewardRedemption`
=> Add Channel Points API

composer.json
- Added myself to `composer.json`
- Bumped minimum PHP version to 7.4
=> composer.json Adjustments

spec/NewTwitchApi/NewTwitchApiSpec.php, spec/NewTwitchApi/Resources/SubscriptionsApiSpec.php, spec/NewTwitchApi/Resources/TeamsApiSpec.php, src/NewTwitchApi/NewTwitchApi.php, src/NewTwitchApi/Resources/SubscriptionsApi.php, src/NewTwitchApi/Resources/TeamsApi.php
This PR adds the new endpoints announced today.
Announcement: https://discuss.dev.twitch.tv/t/the-latest-twitch-api-endpoints-for-twitch-teams-and-subscriptions/30838
=> Add new endpoints (teams and check user sub)

spec/NewTwitchApi/NewTwitchApiSpec.php, spec/NewTwitchApi/Resources/ChannelsApiSpec.php, spec/NewTwitchApi/Resources/UsersApiSpec.php, spec/NewTwitchApi/Resources/VideosApiSpec.php, src/NewTwitchApi/NewTwitchApi.php, src/NewTwitchApi/Resources/ChannelsApi.php, src/NewTwitchApi/Resources/UsersApi.php, src/NewTwitchApi/Resources/VideosApi.php
**NEW FUNCTIONS**
- Added ChannelsApi
- Added ChannelsApi->getChannelInfo
- Added ChannelsApi->getChannelEditors
- Added UsersApi->getUserBlockList
- Added UsersApi->blockUser
- Added UsersApi->unblockUser
- Added VideosApi->deleteVideos
=> Add Endpoints for March 2021

spec/NewTwitchApi/Resources/StreamsApiSpec.php, src/NewTwitchApi/Resources/StreamsApi.php
Add `StreamsApi->getFollowedStreams`
=> Add getFollowedStreams

spec/NewTwitchApi/NewTwitchApiSpec.php, spec/NewTwitchApi/Resources/PollsApiSpec.php, spec/NewTwitchApi/Resources/PredictionsApiSpec.php, src/NewTwitchApi/NewTwitchApi.php, src/NewTwitchApi/Resources/PollsApi.php, src/NewTwitchApi/Resources/PredictionsApi.php
**NEW FEATURES**
- Add `PollsApi`
- Add `PollsApi` -> `getPolls`
- Add `PredictionsApi`
- Add `PredictionsApi` -> `getPredictions`
=> Add Polls and Predictions Classes & GET Endpoints

spec/NewTwitchApi/NewTwitchApiSpec.php, spec/NewTwitchApi/Resources/AdsApiSpec.php, spec/NewTwitchApi/Resources/ChannelPointsApiSpec.php, spec/NewTwitchApi/Resources/ChannelsApiSpec.php, spec/NewTwitchApi/Resources/ModerationApiSpec.php, spec/NewTwitchApi/Resources/PollsApiSpec.php, spec/NewTwitchApi/Resources/PredictionsApiSpec.php, spec/NewTwitchApi/Resources/StreamsApiSpec.php, spec/NewTwitchApi/Resources/TagsApiSpec.php, src/NewTwitchApi/NewTwitchApi.php, src/NewTwitchApi/Resources/AdsApi.php, src/NewTwitchApi/Resources/ChannelPointsApi.php, src/NewTwitchApi/Resources/ChannelsApi.php, src/NewTwitchApi/Resources/ModerationApi.php, src/NewTwitchApi/Resources/PollsApi.php, src/NewTwitchApi/Resources/PredictionsApi.php, src/NewTwitchApi/Resources/StreamsApi.php, src/NewTwitchApi/Resources/SubscriptionsApi.php, src/NewTwitchApi/Resources/TagsApi.php
Very, very, VERY large commit!
Now that body parameters work, we have tons of changes and lots of tickets to close :)
**BREAKING CHANGES**
- Remove `SubscriptionsApi`->`getSubscriptionEvents` #107 (pulled by Twitch)
- Remove `StreamsApi`->`getChannelInfo` #105 (duplicate, moved to `ChannelsApi`)
- Remove `StreamsApi`->`getStreamTags` #104 (duplicate, moved to `TagsApi`)
- Remove `StreamsApi`->`getStreamsMetadata` #103 (pulled by Twitch)
**NEW FUNCTIONS**
- Add `AdsApi`
- Add `ChannelsApi`->`modifyChannelInfo`
- Add `ChannelPointsApi`->`createCustomReward`
- Add `ChannelPointsApi`->`updateCustomReward`
- Add `ChannelPointsApi`->`updateRedemptionStatus`
- Add `ModerationApi`->`checkAutoModStatus`
- Add `ModerationApi`->`manageHeldAutoModMessage`
- Add `PollsApi`->`createPoll`
- Add …
=> v5 Release

README.md, spec/NewTwitchApi/Resources/ChatApiSpec.php, src/NewTwitchApi/Resources/ChatApi.php
**NEW FEATURES**
- Added `ChatApi`->`GetChannelEmotes`
- Added `ChatApi`->`GetGlobalEmotes`
- Added `ChatApi`->`GetEmotesSet`
=> Add Emote Endpoints

spec/NewTwitchApi/Resources/EventSubApiSpec.php, src/NewTwitchApi/Resources/EventSubApi.php
Fix URL for `EventSub`->`subscribeToChannelSubscriptionGift`
Add `EventSub`->`subscribeToChannelSubscriptionMessage
=> v5.0.4: EventSub

spec/TwitchApi/Resources/EventSubApiSpec.php, src/Resources/EventSubApi.php
the "after" param should be supporteded according the docs https://dev.twitch.tv/docs/api/reference#get-eventsub-subscriptions
=> getEventSubSubscription should support "after" param

src/Resources/EntitlementsApi.php
https://dev.twitch.tv/docs/api/reference#update-drops-entitlements
Tested and working
=> Add Update Drops Entitlements endpoint
